# Assignment 1
# Python and NumPy exercises

## Deadline: Thursday, September 28 at 8:00 PM
## The assignment must be submitted in the form of a Jupyter notebook and uploaded to eClass.

## Marks:
- Part 1. Types and Operations. 0.5 marks.
- Part 2. Loops and Functions. 1 mark.
- Part 3. NumPy. 1 mark.
- Total = 2.5 marks.

## Notes:
Some partial code is provided; your solution should use that partial code. The solution doesn't need to be pretty! Make sure the code runs without errors. All required imports will be provided for you; you shouldn't import any other modules. You may need to check with the documentation for Python or NumPy, or other online sources. There are multiple solutions for most tasks.

In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Part 1. Types and Operations

In [2]:
# Use these variable definitions in the following exercises
a = 5
b = 10
string1 = 'Hello'
string2 = 'World'
list1 = [7, 42, 13, -42]
list2 = ['Hello', 'World']
list3 = ["I'm", 'ready', 'to', 'Python']

# 1.1. In each of the following statements, replace None with the boolean expression corresponding to the text
print('a is exactly equal to b:', a == b)
print('Twice a is exactly equal to b:', (2 * a) == b)
print('a is greater than b:', a > b)
print('a is less than b:', a < b)

# 1.2. In each of the following statements, replace None with the expression corresponding to the text
print('The first, second and fourth elements in list1:', list1[0], list1[1], list1[3])
print('The last element in list1:', list1[-1])
print('The slice of list1 from the second to the third value, inclusive:', list1[1:3])
print('list1 with the number 43 appended to the end of the list:', list1.append(43))
print('The concatenation (using the + operator) of string1 and string2:', string1 + string2)
print('The concatenation (using the + operator) of list1 and list2:', list2 + list3)
print('The concatenation of string1 with itself 10 times using the * operator:', string1 * 10)

a is exactly equal to b: False
Twice a is exactly equal to b: True
a is greater than b: False
a is less than b: True
The first, second and fourth elements in list1: 7 42 -42
The last element in list1: -42
The slice of list1 from the second to the third value, inclusive: [42, 13]
list1 with the number 43 appended to the end of the list: None
The concatenation (using the + operator) of string1 and string2: HelloWorld
The concatenation (using the + operator) of list1 and list2: ['Hello', 'World', "I'm", 'ready', 'to', 'Python']
The concatenation of string1 with itself 10 times using the * operator: HelloHelloHelloHelloHelloHelloHelloHelloHelloHello


## Part 2. Loops and Functions

2.1. Write a `for` loop that prints out all integers in the range 0 to 1000 inclusive that are divisible by both 3 and 5. You can use the optional end parameter to print to replace the default newline with a space. e.g. print('something', end=' ')

2.2. Write a function that takes as input a list of numbers and returns the product of all the numbers in the list. You can assume that every element of the list is an int or a float.
    
3.3. Write a function that takes a positive integer >= 2 as input and returns `True` if the number is prime and `False` otherwise. A number p is prime if it is divisible only by itself and 1, i.e. `p % n != 0` for all n >= 2 and < p. You can assume that the input value is a positive integer >= 2.

In [3]:
# 2.1. Write a for loop that prints out all integers in the range 0 to 1000 inclusive that are divisible by both 3 and 5
for i in range(1001):
    if i % 3 == 0 and i % 5 == 0:
        print(i, end=' ')

# 2.2. Write a function that takes as input a list of numbers and returns the product of all the numbers in the list
#    You can assume that every element of the list is an int or a float
def product(number_list):
    result = 1
    for x in number_list:
        result = result * x
    return result

# Test the product function
print(product([2, 4, 6, 8, 10]))

# 3.3. Write a function that takes a positive integer >= 2 as input and returns `True` if the number is prime and `False` otherwise.
# A number p is prime if it is divisible only by itself and 1, i.e. `p % n != 0` for all n >= 2 and < p.
# You can assume that the input value is a positive integer >= 2.
def is_prime(n):
    for i in range(2, n): 
        if n % i == 0:
            return False
    return True

# Test the is_prime function
print(is_prime(71))
print(is_prime(48))

0 15 30 45 60 75 90 105 120 135 150 165 180 195 210 225 240 255 270 285 300 315 330 345 360 375 390 405 420 435 450 465 480 495 510 525 540 555 570 585 600 615 630 645 660 675 690 705 720 735 750 765 780 795 810 825 840 855 870 885 900 915 930 945 960 975 990 3840
True
False


## Part 3. NumPy

In [4]:
# Part 3

# 3.1. Create arrays from each of the three given lists
# Then print the arrays and the shape of each array
list1 = [1,2,3]
list2 = [[1,2,3],[1,2,3]]
list3 = [[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]
a1 = np.array(list1)
a2 = np.array(list2)
a3 = np.array(list3)
print('a1 =\n', a1)
print('a1.shape =', a1.shape)
print('a2 =\n', a2)
print('a2.shape =', a2.shape)
print('a3 =\n', a3)
print('a3.shape =', a3.shape)

# 3.2. Create a 3x4 array full of zeros
zero_array = np.zeros((3,4))
print('zero_array =\n', zero_array)

# 3.3. Using the given random number generator object,
# Create a 2x4 array of random integers in the range 10 to 20 inclusive
rng = np.random.default_rng()
random_array = rng.integers(10, 20, size=(2,4), endpoint=True)
print('random_array =\n', random_array)

# 3.4. Create an array that contains every even number from 0 to 20 inclusive
range_array = np.arange(0, 21, 2)
print('range_array =\n', range_array)

# Use the array X for the following tasks
X = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23]])
print('X =\n', X)
print('X.shape =', X.shape)

# 3.5. With X, use slicing to select the third and sixth row and the second column
# The returned array should have shape (2,1)
sliced_X = X[(2,5),:1]
print('sliced_X =\n', sliced_X)
print('sliced_X.shape =', sliced_X.shape)

# 3.6. Reshape X into array with shape (6,4)
reshaped_X = X.reshape(6, 4)
print('reshaped_X =\n', reshaped_X)
print('reshaped_X.shape =', reshaped_X.shape)

# 3.7. Create a matrix with the same shape of X but with only ones
my_ones = np.ones(X.shape)
print('my_ones =\n', my_ones)
print('my_ones.shape =', my_ones.shape)

# Concatenate my_ones with X first on rows (axis=0) then on columns (axis=1)
row_concat = np.concatenate((my_ones, X), axis=0)
print('Shape after row concatenation {}'.format(row_concat.shape))
column_concat = np.concatenate((my_ones, X), axis=1)
print('Shape after column concatenation {}'.format(column_concat.shape))

# 3.8. Create a new array of ones of shape (1,3) add it to X using broadcasting
new_array = 10 * np.ones((1,3))
broadcasting_ex = X + new_array
print('Result of broadcasted sum of \n {} \n with {} is \n {}'.format(X, new_array, broadcasting_ex))

# 3.9. Create an array A of shape (4,6) composed of random integers in the range (0,10) inclusive
# Create an array b of shape (1,6) composed of every integer from 1 to 6 inclusive
# Then add add b to A by broadcasting, i.e. A + b
A = rng.integers(0, 10, (4,6))
b = np.array([1, 2, 3, 4, 5, 6])
print('A + b =\n', A + b)

# Use this array for the following exercises
C = np.array([[16,64],[-25,4]]) 

# 3.10. Print the mean of all the elements of C (replace None with correct numpy function call)
print('The mean of C = {:.2f}'.format(C.mean()))

# 3.11. Print the standard deviation of C
print('The standard deviation of C = {:.2f}'.format(C.std()))

# 3.12. Print the variance of C
print('The variance of C = {:.2f}'.format(C.var()))

# Create two arrays with shape (3,3)
A = rng.integers(5, 10, (3,3))
B = rng.integers(1, 5, (3,3))

# Print the result of elementwise multiplication of A and B 
print('Elementwise multiplication of A and B =\n', A * B)

# Perform matrix multiplication of A and B using dot
# Perform matrix multiplication of A and B using matmul
print('Dot product of A and B =\n', np.dot(A, B))
print('Matrix multiplcation product of A and B =\n', np.matmul(A, B))

a1 =
 [1 2 3]
a1.shape = (3,)
a2 =
 [[1 2 3]
 [1 2 3]]
a2.shape = (2, 3)
a3 =
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
a3.shape = (2, 2, 3)
zero_array =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
random_array =
 [[15 17 14 18]
 [19 12 18 18]]
range_array =
 [ 0  2  4  6  8 10 12 14 16 18 20]
X =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
X.shape = (8, 3)
sliced_X =
 [[ 6]
 [15]]
sliced_X.shape = (2, 1)
reshaped_X =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
reshaped_X.shape = (6, 4)
my_ones =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
my_ones.shape = (8, 3)
Shape after row concatenation (16, 3)
Shape after column concatenation (8, 6)
Result of broadcasted sum of 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
 with [[10. 10. 10.]] is 
 [[10. 11. 12.]
 [13. 14. 15.]
 [16.